version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - iotnet

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/iot_management
      - JWT_SECRET=your_jwt_secret
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - iotnet

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      - iotnet

volumes:
  mongo-data:

networks:
  iotnet:
    driver: bridge 